"""Initial migration - usuarios y tablas relacionadas

Revision ID: afbe24b40bc9
Revises: 
Create Date: 2025-10-04 20:08:50.401352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afbe24b40bc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_premios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('puntos_requeridos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('stock_disponible', sa.Integer(), nullable=True),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_premios_activo'), 'catalogo_premios', ['activo'], unique=False)
    op.create_table('reglas_conversion_puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('puntos_por_peso', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_conversion_puntos_activo'), 'reglas_conversion_puntos', ['activo'], unique=False)
    op.create_table('tipo_alcance_regla_de_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tipo_regla', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_alcance_regla_de_precio_id_ext'), 'tipo_alcance_regla_de_precio', ['id_ext'], unique=True)
    op.create_table('tipo_nivel_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nivel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('puntaje_min', sa.Integer(), nullable=False),
    sa.Column('puntaje_max', sa.Integer(), nullable=True),
    sa.Column('beneficios', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel')
    )
    op.create_index(op.f('ix_tipo_nivel_usuario_id_ext'), 'tipo_nivel_usuario', ['id_ext'], unique=True)
    op.create_table('tipos_barril',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_barril_id_ext'), 'tipos_barril', ['id_ext'], unique=True)
    op.create_table('tipos_estado_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permite_ventas', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estado')
    )
    op.create_index(op.f('ix_tipos_estado_equipo_id_ext'), 'tipos_estado_equipo', ['id_ext'], unique=True)
    op.create_table('tipos_estilo_cerveza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('estilo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estilo')
    )
    op.create_index(op.f('ix_tipos_estilo_cerveza_id_ext'), 'tipos_estilo_cerveza', ['id_ext'], unique=True)
    op.create_table('tipos_metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requiere_autorizacion', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metodo_pago')
    )
    op.create_index(op.f('ix_tipos_metodo_pago_id_ext'), 'tipos_metodo_pago', ['id_ext'], unique=True)
    op.create_table('tipos_rol_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_index(op.f('ix_tipos_rol_usuario_id_ext'), 'tipos_rol_usuario', ['id_ext'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codigo_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sexo', sa.Enum('FEMENINO', 'MASCULINO', name='tiposexo'), nullable=True),
    sa.Column('fecha_nac', sa.Date(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('intentos_login_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_codigo_cliente'), 'usuarios', ['codigo_cliente'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_fecha_creacion'), 'usuarios', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_usuarios_id_ext'), 'usuarios', ['id_ext'], unique=True)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_index(op.f('ix_usuarios_tipo_registro'), 'usuarios', ['tipo_registro'], unique=False)
    op.create_table('canjes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_premio', sa.Integer(), nullable=False),
    sa.Column('puntos_utilizados', sa.Integer(), nullable=False),
    sa.Column('fecha_canje', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['id_premio'], ['catalogo_premios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canjes_fecha_canje'), 'canjes', ['fecha_canje'], unique=False)
    op.create_index(op.f('ix_canjes_id_premio'), 'canjes', ['id_premio'], unique=False)
    op.create_index(op.f('ix_canjes_id_usuario'), 'canjes', ['id_usuario'], unique=False)
    op.create_table('cervezas',
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abv', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ibu', sa.Integer(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cervezas_creado_el'), 'cervezas', ['creado_el'], unique=False)
    op.create_index(op.f('ix_cervezas_id_ext'), 'cervezas', ['id_ext'], unique=True)
    op.create_index(op.f('ix_cervezas_nombre'), 'cervezas', ['nombre'], unique=True)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('APROBADO', 'RECHAZADO', 'PENDIENTE', name='tipoestadopago'), nullable=False),
    sa.Column('id_transaccion_proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('motivo_rechazo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['tipos_metodo_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pagos_estado', 'pagos', ['estado'], unique=False)
    op.create_index('idx_pagos_fecha', 'pagos', ['fecha_pago'], unique=False)
    op.create_index('idx_pagos_metodo', 'pagos', ['id_metodo_pago'], unique=False)
    op.create_index('idx_pagos_transaccion', 'pagos', ['id_transaccion_proveedor'], unique=False)
    op.create_index('idx_pagos_venta', 'pagos', ['id_venta'], unique=False)
    op.create_index(op.f('ix_pagos_estado'), 'pagos', ['estado'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_pago'), 'pagos', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_venta'), 'pagos', ['fecha_venta'], unique=False)
    op.create_index(op.f('ix_pagos_id_metodo_pago'), 'pagos', ['id_metodo_pago'], unique=False)
    op.create_index(op.f('ix_pagos_id_venta'), 'pagos', ['id_venta'], unique=False)
    op.create_table('puntos_de_venta',
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('localidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horario_apertura', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horario_cierre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_usuario_socio', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_socio'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_de_venta_creado_el'), 'puntos_de_venta', ['creado_el'], unique=False)
    op.create_index(op.f('ix_puntos_de_venta_id_ext'), 'puntos_de_venta', ['id_ext'], unique=True)
    op.create_table('referidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id_usuario_generador', sa.Integer(), nullable=True),
    sa.Column('id_usuario_referido', sa.Integer(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('puntos_otorgados', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_activacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_generador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_referido'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referidos_codigo'), 'referidos', ['codigo'], unique=True)
    op.create_index(op.f('ix_referidos_id_ext'), 'referidos', ['id_ext'], unique=True)
    op.create_table('reglas_de_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='tipoprioridadregla'), nullable=False),
    sa.Column('multiplicador', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('dias_semana', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_de_precio_esta_activo'), 'reglas_de_precio', ['esta_activo'], unique=False)
    op.create_index(op.f('ix_reglas_de_precio_fecha_hora_fin'), 'reglas_de_precio', ['fecha_hora_fin'], unique=False)
    op.create_index(op.f('ix_reglas_de_precio_fecha_hora_inicio'), 'reglas_de_precio', ['fecha_hora_inicio'], unique=False)
    op.create_index(op.f('ix_reglas_de_precio_id_ext'), 'reglas_de_precio', ['id_ext'], unique=True)
    op.create_index(op.f('ix_reglas_de_precio_prioridad'), 'reglas_de_precio', ['prioridad'], unique=False)
    op.create_table('usuarios_metodos_de_pago',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('proveedor_metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['tipos_metodo_pago.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_metodo_pago')
    )
    op.create_table('usuarios_niveles',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_nivel', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('puntaje_actual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_nivel'], ['tipo_nivel_usuario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('usuarios_roles',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_revocacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['tipos_rol_usuario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('cervezas_estilos',
    sa.Column('id_cerveza', sa.Integer(), nullable=False),
    sa.Column('id_estilo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cerveza'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['id_estilo'], ['tipos_estilo_cerveza.id'], ),
    sa.PrimaryKeyConstraint('id_cerveza', 'id_estilo')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id_estado_equipo', sa.Integer(), nullable=False),
    sa.Column('id_barril', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capacidad_actual', sa.Integer(), nullable=False),
    sa.Column('temperatura_actual', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ultima_limpieza', sa.Date(), nullable=True),
    sa.Column('proxima_limpieza', sa.Date(), nullable=True),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('id_punto_de_venta', sa.Integer(), nullable=True),
    sa.Column('id_cerveza', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barril'], ['tipos_barril.id'], ),
    sa.ForeignKeyConstraint(['id_cerveza'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['id_estado_equipo'], ['tipos_estado_equipo.id'], ),
    sa.ForeignKeyConstraint(['id_punto_de_venta'], ['puntos_de_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_id_ext'), 'equipos', ['id_ext'], unique=True)
    op.create_table('precios_cervezas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cerveza', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_cerveza'], ['cervezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precios_cervezas_fecha_inicio'), 'precios_cervezas', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_precios_cervezas_id_cerveza'), 'precios_cervezas', ['id_cerveza'], unique=False)
    op.create_table('reglas_de_precios_alcance',
    sa.Column('id_regla_de_precio', sa.Integer(), nullable=False),
    sa.Column('tipo_alcance', sa.Enum('CERVEZA', 'PUNTO_DE_VENTA', 'EQUIPO', name='tipoalcanceregla'), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_regla_de_precio'], ['reglas_de_precio.id'], ),
    sa.PrimaryKeyConstraint('id_regla_de_precio', 'tipo_alcance', 'id_entidad')
    )
    op.create_table('transacciones_puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('puntos_ganados', sa.Integer(), nullable=False),
    sa.Column('puntos_canjeados', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Integer(), nullable=False),
    sa.Column('saldo_posterior', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_canje', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_transaccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_canje'], ['canjes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transacciones_puntos_fecha', 'transacciones_puntos', ['fecha'], unique=False)
    op.create_index('idx_transacciones_puntos_usuario', 'transacciones_puntos', ['id_usuario'], unique=False)
    op.create_index('idx_transacciones_puntos_usuario_fecha', 'transacciones_puntos', ['id_usuario', 'fecha'], unique=False)
    op.create_index(op.f('ix_transacciones_puntos_fecha'), 'transacciones_puntos', ['fecha'], unique=False)
    op.create_index(op.f('ix_transacciones_puntos_id_usuario'), 'transacciones_puntos', ['id_usuario'], unique=False)
    op.create_table('reglas_de_precio_entidades',
    sa.Column('id_regla_de_precio', sa.Integer(), nullable=False),
    sa.Column('id_cerveza', sa.Integer(), nullable=False),
    sa.Column('id_punto_de_venta', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cerveza'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['id_punto_de_venta'], ['puntos_de_venta.id'], ),
    sa.ForeignKeyConstraint(['id_regla_de_precio'], ['reglas_de_precio.id'], ),
    sa.PrimaryKeyConstraint('id_regla_de_precio', 'id_cerveza', 'id_punto_de_venta', 'id_equipo')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ext', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('cantidad_ml', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_aplicado', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cerveza', sa.Integer(), nullable=True),
    sa.Column('id_equipo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cerveza'], ['cervezas.id'], ),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id', 'fecha_hora')
    )
    op.create_index('idx_ventas_cerveza', 'ventas', ['id_cerveza'], unique=False)
    op.create_index('idx_ventas_equipo', 'ventas', ['id_equipo'], unique=False)
    op.create_index('idx_ventas_fecha_cerveza', 'ventas', ['fecha_hora', 'id_cerveza'], unique=False)
    op.create_index('idx_ventas_fecha_hora', 'ventas', ['fecha_hora'], unique=False)
    op.create_index('idx_ventas_fecha_usuario', 'ventas', ['fecha_hora', 'id_usuario'], unique=False)
    op.create_index('idx_ventas_usuario', 'ventas', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_ventas_fecha_hora'), 'ventas', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_ventas_id_cerveza'), 'ventas', ['id_cerveza'], unique=False)
    op.create_index(op.f('ix_ventas_id_equipo'), 'ventas', ['id_equipo'], unique=False)
    op.create_index(op.f('ix_ventas_id_ext'), 'ventas', ['id_ext'], unique=True)
    op.create_index(op.f('ix_ventas_id_usuario'), 'ventas', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_id_usuario'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id_ext'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id_equipo'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id_cerveza'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha_hora'), table_name='ventas')
    op.drop_index('idx_ventas_usuario', table_name='ventas')
    op.drop_index('idx_ventas_fecha_usuario', table_name='ventas')
    op.drop_index('idx_ventas_fecha_hora', table_name='ventas')
    op.drop_index('idx_ventas_fecha_cerveza', table_name='ventas')
    op.drop_index('idx_ventas_equipo', table_name='ventas')
    op.drop_index('idx_ventas_cerveza', table_name='ventas')
    op.drop_table('ventas')
    op.drop_table('reglas_de_precio_entidades')
    op.drop_index(op.f('ix_transacciones_puntos_id_usuario'), table_name='transacciones_puntos')
    op.drop_index(op.f('ix_transacciones_puntos_fecha'), table_name='transacciones_puntos')
    op.drop_index('idx_transacciones_puntos_usuario_fecha', table_name='transacciones_puntos')
    op.drop_index('idx_transacciones_puntos_usuario', table_name='transacciones_puntos')
    op.drop_index('idx_transacciones_puntos_fecha', table_name='transacciones_puntos')
    op.drop_table('transacciones_puntos')
    op.drop_table('reglas_de_precios_alcance')
    op.drop_index(op.f('ix_precios_cervezas_id_cerveza'), table_name='precios_cervezas')
    op.drop_index(op.f('ix_precios_cervezas_fecha_inicio'), table_name='precios_cervezas')
    op.drop_table('precios_cervezas')
    op.drop_index(op.f('ix_equipos_id_ext'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_table('cervezas_estilos')
    op.drop_table('usuarios_roles')
    op.drop_table('usuarios_niveles')
    op.drop_table('usuarios_metodos_de_pago')
    op.drop_index(op.f('ix_reglas_de_precio_prioridad'), table_name='reglas_de_precio')
    op.drop_index(op.f('ix_reglas_de_precio_id_ext'), table_name='reglas_de_precio')
    op.drop_index(op.f('ix_reglas_de_precio_fecha_hora_inicio'), table_name='reglas_de_precio')
    op.drop_index(op.f('ix_reglas_de_precio_fecha_hora_fin'), table_name='reglas_de_precio')
    op.drop_index(op.f('ix_reglas_de_precio_esta_activo'), table_name='reglas_de_precio')
    op.drop_table('reglas_de_precio')
    op.drop_index(op.f('ix_referidos_id_ext'), table_name='referidos')
    op.drop_index(op.f('ix_referidos_codigo'), table_name='referidos')
    op.drop_table('referidos')
    op.drop_index(op.f('ix_puntos_de_venta_id_ext'), table_name='puntos_de_venta')
    op.drop_index(op.f('ix_puntos_de_venta_creado_el'), table_name='puntos_de_venta')
    op.drop_table('puntos_de_venta')
    op.drop_index(op.f('ix_pagos_id_venta'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_metodo_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_fecha_venta'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_fecha_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_estado'), table_name='pagos')
    op.drop_index('idx_pagos_venta', table_name='pagos')
    op.drop_index('idx_pagos_transaccion', table_name='pagos')
    op.drop_index('idx_pagos_metodo', table_name='pagos')
    op.drop_index('idx_pagos_fecha', table_name='pagos')
    op.drop_index('idx_pagos_estado', table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_cervezas_nombre'), table_name='cervezas')
    op.drop_index(op.f('ix_cervezas_id_ext'), table_name='cervezas')
    op.drop_index(op.f('ix_cervezas_creado_el'), table_name='cervezas')
    op.drop_table('cervezas')
    op.drop_index(op.f('ix_canjes_id_usuario'), table_name='canjes')
    op.drop_index(op.f('ix_canjes_id_premio'), table_name='canjes')
    op.drop_index(op.f('ix_canjes_fecha_canje'), table_name='canjes')
    op.drop_table('canjes')
    op.drop_index(op.f('ix_usuarios_tipo_registro'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_ext'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fecha_creacion'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_codigo_cliente'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_rol_usuario_id_ext'), table_name='tipos_rol_usuario')
    op.drop_table('tipos_rol_usuario')
    op.drop_index(op.f('ix_tipos_metodo_pago_id_ext'), table_name='tipos_metodo_pago')
    op.drop_table('tipos_metodo_pago')
    op.drop_index(op.f('ix_tipos_estilo_cerveza_id_ext'), table_name='tipos_estilo_cerveza')
    op.drop_table('tipos_estilo_cerveza')
    op.drop_index(op.f('ix_tipos_estado_equipo_id_ext'), table_name='tipos_estado_equipo')
    op.drop_table('tipos_estado_equipo')
    op.drop_index(op.f('ix_tipos_barril_id_ext'), table_name='tipos_barril')
    op.drop_table('tipos_barril')
    op.drop_index(op.f('ix_tipo_nivel_usuario_id_ext'), table_name='tipo_nivel_usuario')
    op.drop_table('tipo_nivel_usuario')
    op.drop_index(op.f('ix_tipo_alcance_regla_de_precio_id_ext'), table_name='tipo_alcance_regla_de_precio')
    op.drop_table('tipo_alcance_regla_de_precio')
    op.drop_index(op.f('ix_reglas_conversion_puntos_activo'), table_name='reglas_conversion_puntos')
    op.drop_table('reglas_conversion_puntos')
    op.drop_index(op.f('ix_catalogo_premios_activo'), table_name='catalogo_premios')
    op.drop_table('catalogo_premios')
    # ### end Alembic commands ###
